PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

-- ─── TRIPS ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS trips (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  title               TEXT    NOT NULL,
  emoji               TEXT    NOT NULL DEFAULT '🗺️',
  status              TEXT    NOT NULL DEFAULT 'draft'
                              CHECK(status IN ('draft','planning','confirmed','ready','completed','archived')),
  start_date          TEXT,   -- ISO date YYYY-MM-DD, nullable (open-ended trips)
  end_date            TEXT,   -- ISO date YYYY-MM-DD, nullable
  tags                TEXT    NOT NULL DEFAULT '[]',  -- JSON array of strings
  notes               TEXT,   -- Tiptap JSON (rich text), nullable
  cover_gradient      TEXT    NOT NULL DEFAULT 'warm-brown', -- key into gradient presets
  distance_total_m    INTEGER,  -- sum of all leg distances, cached
  distance_synced_at  TEXT,     -- ISO datetime of last TomTom sync
  external_id         TEXT      UNIQUE DEFAULT (lower(hex(randomblob(16)))),  -- stable UUID for .trippack dedup
  created_at          TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at          TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- ─── DAYS ───────────────────────────────────────────────────────────────────
-- Generated by days.service.ts when a trip's date range is set/changed.
-- One row per calendar date within the trip's range.

CREATE TABLE IF NOT EXISTS days (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  trip_id     INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  date        TEXT    NOT NULL,   -- ISO date YYYY-MM-DD
  title       TEXT,               -- optional day title
  subtitle    TEXT,               -- optional day subtitle
  notes       TEXT,               -- Tiptap JSON, nullable
  created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
  UNIQUE(trip_id, date)
);

CREATE INDEX IF NOT EXISTS idx_days_trip_id ON days(trip_id);

-- ─── ACTIVITY TYPES ─────────────────────────────────────────────────────────
-- User-manageable activity types. Replaces the previous CHECK-constrained enum
-- so users can create/rename/delete types at runtime.

CREATE TABLE IF NOT EXISTS activity_types (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  name       TEXT    NOT NULL UNIQUE,
  icon_name  TEXT,   -- optional Lucide icon identifier
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- Reason: activity_types seed is placed here (before the SEED DATA marker)
-- because the FK constraint on activities.activity_type_id requires at least
-- the default types to exist before any activity can be inserted.
INSERT OR IGNORE INTO activity_types (id, name, icon_name, sort_order) VALUES
  (1, 'attraction', 'camera',       0),
  (2, 'food',       'utensils',     1),
  (3, 'shopping',   'shopping-bag', 2),
  (4, 'outdoors',   'tree-pine',    3),
  (5, 'cultural',   'landmark',     4),
  (6, 'note',       'file-text',    5),
  (7, 'other',      'tag',          6);

-- ─── ACTIVITIES ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS activities (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  day_id              INTEGER REFERENCES days(id) ON DELETE CASCADE,
  -- Reason: day_id is nullable to support trip-level activities (e.g. places of
  -- interest) that are not tied to a specific day. trip_id CASCADE deletes them.
  trip_id             INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  title               TEXT    NOT NULL,
  activity_type_id    INTEGER NOT NULL REFERENCES activity_types(id),

  -- Time window (both optional; end_time requires start_time in app logic)
  start_time          TEXT,   -- HH:MM
  end_time            TEXT,   -- HH:MM

  sort_order          INTEGER NOT NULL DEFAULT 0,

  -- Content
  notes               TEXT,   -- plain text or Tiptap JSON, nullable

  -- Locatable mixin — geocodable place for the map tab
  location            TEXT,   -- free-text place for geocoding, nullable
  lat                 REAL,   -- geocoded latitude, nullable
  lng                 REAL,   -- geocoded longitude, nullable

  created_at          TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at          TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_activities_day_id   ON activities(day_id);
CREATE INDEX IF NOT EXISTS idx_activities_trip_id  ON activities(trip_id);
CREATE INDEX IF NOT EXISTS idx_activities_type_id  ON activities(activity_type_id);


-- ─── CHECKLIST TEMPLATES ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS checklist_templates (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  name        TEXT    NOT NULL,
  icon_name   TEXT,             -- Lucide icon name string
  is_base     INTEGER NOT NULL DEFAULT 0,  -- 1 = always included, cannot be deleted
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS template_items (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  template_id INTEGER NOT NULL REFERENCES checklist_templates(id) ON DELETE CASCADE,
  label       TEXT    NOT NULL,
  category    TEXT    NOT NULL DEFAULT 'other',
  sort_order  INTEGER NOT NULL DEFAULT 0
);

-- ─── CHECKLIST ITEMS (per trip) ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS checklist_items (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  trip_id     INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  label       TEXT    NOT NULL,
  category    TEXT    DEFAULT NULL,
  is_checked  INTEGER NOT NULL DEFAULT 0,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  source      TEXT    NOT NULL DEFAULT 'trip'
                      CHECK(source IN ('template','trip')),
  created_at  TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_checklist_trip ON checklist_items(trip_id);

-- ─── SETTINGS ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS settings (
  key         TEXT PRIMARY KEY,
  value       TEXT NOT NULL   -- JSON-encoded value
);

-- ─── TRIGGERS: updated_at ────────────────────────────────────────────────────

CREATE TRIGGER IF NOT EXISTS trips_updated_at
  AFTER UPDATE ON trips
  BEGIN UPDATE trips SET updated_at = datetime('now') WHERE id = NEW.id; END;

CREATE TRIGGER IF NOT EXISTS activities_updated_at
  AFTER UPDATE ON activities
  BEGIN UPDATE activities SET updated_at = datetime('now') WHERE id = NEW.id; END;

-- ─── RESERVATIONS ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS reservations (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  trip_id          INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  day_id           INTEGER REFERENCES days(id) ON DELETE SET NULL,
  type             TEXT NOT NULL CHECK(type IN (
                     'lodging','flight','train','bus','ferry','rental_car','restaurant','other'
                   )),
  title            TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending'
                   CHECK(status IN ('pending','confirmed','cancelled')),
  confirmation_ref TEXT,
  notes            TEXT,
  cost_amount      REAL,
  cost_currency    TEXT DEFAULT 'EUR',
  details          TEXT NOT NULL DEFAULT '{}',
  sort_order       INTEGER NOT NULL DEFAULT 0,
  -- Locatable mixin — geocodable place for the map tab
  location         TEXT,   -- free-text place for geocoding, nullable
  lat              REAL,   -- geocoded latitude, nullable
  lng              REAL,   -- geocoded longitude, nullable
  -- Reason: type-specific fields stored as JSON. Validated by Zod schemas before
  -- reaching the DB. May be normalised into dedicated columns in a future version
  -- if query performance on details fields becomes necessary.
  created_at       TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at       TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_res_trip ON reservations(trip_id);
CREATE INDEX IF NOT EXISTS idx_res_day  ON reservations(day_id);

CREATE TRIGGER IF NOT EXISTS reservations_updated_at
  AFTER UPDATE ON reservations
  BEGIN UPDATE reservations SET updated_at = datetime('now') WHERE id = NEW.id; END;

-- ─── ROUTE LEGS ───────────────────────────────────────────────────────────────
-- Caches TomTom routing results between consecutive geocoded points on a trip.
-- Keyed by (trip_id, from_lat, from_lng, to_lat, to_lng) so the same pair is
-- never fetched twice even if points appear on different trips.
-- Reason: storing the polyline as encoded JSON avoids a separate points table
-- while keeping rendering simple (decode JSON array of {lat,lng} in the client).

CREATE TABLE IF NOT EXISTS route_legs (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  trip_id          INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  from_lat         REAL    NOT NULL,
  from_lng         REAL    NOT NULL,
  to_lat           REAL    NOT NULL,
  to_lng           REAL    NOT NULL,
  distance_m       INTEGER NOT NULL,  -- metres
  duration_s       INTEGER NOT NULL,  -- seconds
  polyline         TEXT    NOT NULL,  -- JSON array of {lat, lng} points
  travel_mode      TEXT    NOT NULL DEFAULT 'car'
                           CHECK(travel_mode IN ('car','pedestrian','bicycle')),
  fetched_at       TEXT    NOT NULL DEFAULT (datetime('now')),
  UNIQUE(trip_id, from_lat, from_lng, to_lat, to_lng, travel_mode)
);

CREATE INDEX IF NOT EXISTS idx_route_legs_trip ON route_legs(trip_id);

-- ─── LEG MODES ─────────────────────────────────────────────────────────────────
-- User-selected travel mode per coord pair per trip.
-- Keyed by (trip_id, from_lat, from_lng, to_lat, to_lng).
-- The sync route reads this table to decide which TomTom mode to request per leg.
-- Defaults to 'car' when no override exists.

CREATE TABLE IF NOT EXISTS leg_modes (
  trip_id     INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  from_lat    REAL    NOT NULL,
  from_lng    REAL    NOT NULL,
  to_lat      REAL    NOT NULL,
  to_lng      REAL    NOT NULL,
  travel_mode TEXT    NOT NULL DEFAULT 'car'
              CHECK(travel_mode IN ('car','pedestrian','bicycle')),
  PRIMARY KEY (trip_id, from_lat, from_lng, to_lat, to_lng)
);

-- ─── INDEXES ──────────────────────────────────────────────────────────────────

-- Composite index for the lodging overlap check which filters by both
-- trip_id and type. The existing trip_id index is insufficient for this query.
CREATE INDEX IF NOT EXISTS idx_res_trip_type
  ON reservations(trip_id, type);

-- ─── SEED DATA ────────────────────────────────────────────────────────────────

-- Default checklist templates seeded on first run.
-- Guarded with INSERT OR IGNORE so re-running migrations is safe.

INSERT OR IGNORE INTO checklist_templates (id, name, icon_name, is_base, sort_order)
VALUES
  (1, 'Always Packed',  'Star',        1, 0),
  (2, 'Tech Kit',       'Smartphone',  0, 1),
  (3, 'Beach / Warm',   'Sun',         0, 2),
  (4, 'Cold Weather',   'Mountain',    0, 3);

INSERT OR IGNORE INTO template_items (template_id, label, category, sort_order) VALUES
  -- Always Packed
  (1, 'Passport / ID',        'documents', 0),
  (1, 'Travel insurance',     'documents', 1),
  (1, 'Phone + charger',      'tech',      2),
  (1, 'Wallet + cards',       'documents', 3),
  (1, 'Medication',           'health',    4),
  (1, 'Travel adapter',       'tech',      5),
  -- Tech Kit
  (2, 'Laptop + charger',     'tech', 0),
  (2, 'USB-C hub',            'tech', 1),
  (2, 'Power bank',           'tech', 2),
  (2, 'Camera + memory card', 'tech', 3),
  -- Beach / Warm
  (3, 'Sunscreen SPF50+',     'toiletries', 0),
  (3, 'Swimwear',             'clothing',   1),
  (3, 'Flip flops',           'clothing',   2),
  (3, 'Beach towel',          'other',      3),
  (3, 'Sunglasses',           'clothing',   4),
  -- Cold Weather
  (4, 'Thermal base layers',  'clothing', 0),
  (4, 'Warm jacket',          'clothing', 1),
  (4, 'Gloves + scarf',       'clothing', 2),
  (4, 'Wool socks',           'clothing', 3),
  (4, 'Boots',                'clothing', 4);

-- Default settings
INSERT OR IGNORE INTO settings (key, value) VALUES
  ('theme',         '"dark"'),
  ('date_format',   '"DD MMM YYYY"'),
  ('time_areas',    '{"morning":{"label":"Morning","start":6,"end":12},"noon":{"label":"Noon","start":12,"end":13},"afternoon":{"label":"Afternoon","start":13,"end":17},"evening":{"label":"Evening","start":17,"end":20},"night":{"label":"Night","start":20,"end":24},"anytime":{"label":"Anytime","start":0,"end":24}}'),
  ('tomtom_api_key','""');
