PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

-- ─── TRIPS ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS trips (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  title               TEXT    NOT NULL,
  emoji               TEXT    NOT NULL DEFAULT '🗺️',
  status              TEXT    NOT NULL DEFAULT 'draft'
                              CHECK(status IN ('draft','planning','confirmed','ready','completed','archived')),
  start_date          TEXT,   -- ISO date YYYY-MM-DD, nullable (open-ended trips)
  end_date            TEXT,   -- ISO date YYYY-MM-DD, nullable
  tags                TEXT    NOT NULL DEFAULT '[]',  -- JSON array of strings
  notes               TEXT,   -- Tiptap JSON (rich text), nullable
  cover_gradient      TEXT    NOT NULL DEFAULT 'warm-brown', -- key into gradient presets
  distance_total_m    INTEGER,  -- sum of all leg distances, cached
  distance_synced_at  TEXT,     -- ISO datetime of last TomTom sync
  created_at          TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at          TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- ─── DAYS ───────────────────────────────────────────────────────────────────
-- Generated by days.service.ts when a trip's date range is set/changed.
-- One row per calendar date within the trip's range.

CREATE TABLE IF NOT EXISTS days (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  trip_id     INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  date        TEXT    NOT NULL,   -- ISO date YYYY-MM-DD
  title       TEXT,               -- optional day title
  subtitle    TEXT,               -- optional day subtitle
  notes       TEXT,               -- Tiptap JSON, nullable
  created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
  UNIQUE(trip_id, date)
);

CREATE INDEX IF NOT EXISTS idx_days_trip_id ON days(trip_id);

-- ─── ACTIVITIES ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS activities (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  day_id              INTEGER REFERENCES days(id) ON DELETE CASCADE,
  -- Reason: day_id is nullable to support trip-level activities (e.g. places of
  -- interest) that are not tied to a specific day. trip_id CASCADE deletes them.
  trip_id             INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  title               TEXT    NOT NULL,
  activity_type       TEXT    NOT NULL DEFAULT 'note'
                              CHECK(activity_type IN ('attraction','food','shopping','outdoors','cultural','note','other')),

  -- Time window (both optional; end_time requires start_time in app logic)
  start_time          TEXT,   -- HH:MM
  end_time            TEXT,   -- HH:MM

  sort_order          INTEGER NOT NULL DEFAULT 0,

  -- Content
  notes               TEXT,   -- plain text or Tiptap JSON, nullable

  -- Locatable mixin — geocodable place for the map tab
  location            TEXT,   -- free-text place for geocoding, nullable
  lat                 REAL,   -- geocoded latitude, nullable
  lng                 REAL,   -- geocoded longitude, nullable

  created_at          TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at          TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_activities_day_id  ON activities(day_id);
CREATE INDEX IF NOT EXISTS idx_activities_trip_id ON activities(trip_id);


-- ─── CHECKLIST TEMPLATES ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS checklist_templates (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  name        TEXT    NOT NULL,
  icon_name   TEXT,             -- Lucide icon name string
  is_base     INTEGER NOT NULL DEFAULT 0,  -- 1 = always included, cannot be deleted
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS template_items (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  template_id INTEGER NOT NULL REFERENCES checklist_templates(id) ON DELETE CASCADE,
  label       TEXT    NOT NULL,
  category    TEXT    NOT NULL DEFAULT 'other',
  sort_order  INTEGER NOT NULL DEFAULT 0
);

-- ─── CHECKLIST ITEMS (per trip) ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS checklist_items (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  trip_id     INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  label       TEXT    NOT NULL,
  category    TEXT    DEFAULT NULL,
  is_checked  INTEGER NOT NULL DEFAULT 0,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  source      TEXT    NOT NULL DEFAULT 'trip'
                      CHECK(source IN ('template','trip')),
  created_at  TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_checklist_trip ON checklist_items(trip_id);

-- ─── SETTINGS ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS settings (
  key         TEXT PRIMARY KEY,
  value       TEXT NOT NULL   -- JSON-encoded value
);

-- ─── TRIGGERS: updated_at ────────────────────────────────────────────────────

CREATE TRIGGER IF NOT EXISTS trips_updated_at
  AFTER UPDATE ON trips
  BEGIN UPDATE trips SET updated_at = datetime('now') WHERE id = NEW.id; END;

CREATE TRIGGER IF NOT EXISTS activities_updated_at
  AFTER UPDATE ON activities
  BEGIN UPDATE activities SET updated_at = datetime('now') WHERE id = NEW.id; END;

-- ─── RESERVATIONS ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS reservations (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  trip_id          INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  day_id           INTEGER REFERENCES days(id) ON DELETE SET NULL,
  type             TEXT NOT NULL CHECK(type IN (
                     'lodging','flight','train','bus','ferry','rental_car','restaurant','other'
                   )),
  title            TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending'
                   CHECK(status IN ('pending','confirmed','cancelled')),
  confirmation_ref TEXT,
  notes            TEXT,
  cost_amount      REAL,
  cost_currency    TEXT DEFAULT 'EUR',
  details          TEXT NOT NULL DEFAULT '{}',
  sort_order       INTEGER NOT NULL DEFAULT 0,
  -- Locatable mixin — geocodable place for the map tab
  location         TEXT,   -- free-text place for geocoding, nullable
  lat              REAL,   -- geocoded latitude, nullable
  lng              REAL,   -- geocoded longitude, nullable
  -- Reason: type-specific fields stored as JSON. Validated by Zod schemas before
  -- reaching the DB. May be normalised into dedicated columns in a future version
  -- if query performance on details fields becomes necessary.
  created_at       TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at       TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_res_trip ON reservations(trip_id);
CREATE INDEX IF NOT EXISTS idx_res_day  ON reservations(day_id);

CREATE TRIGGER IF NOT EXISTS reservations_updated_at
  AFTER UPDATE ON reservations
  BEGIN UPDATE reservations SET updated_at = datetime('now') WHERE id = NEW.id; END;
